#!/usr/bin/env bash
set -eEuo pipefail

SERVICES="pageviews entities wikiload"
PROJECT_ID=bigquery-public-data-staging
IMAGE=wikisync

gcloud builds submit \
  --project "${PROJECT_ID}" \
  --tag "gcr.io/$PROJECT_ID/$IMAGE" \
  .

for SERVICE in $SERVICES
do
  gcloud beta run deploy "$SERVICE" \
    --image "gcr.io/$PROJECT_ID/$IMAGE" \
    --platform "managed" \
    --region "us-central1" \
    --project "${PROJECT_ID}" \
    --concurrency 1 \
    --memory 1G \
    --allow-unauthenticated
done
