#!/bin/bash

UPATH=other/pageviews
URL=https://dumps.wikimedia.org/$UPATH

wget -nv --spider -S -r -A ".gz" -I $UPATH $URL 2>&1 |
  awk 'function base(file, a, n) {n = split(file,a,"/"); return a[n]} \
       $1 == "Content-Length:" {len=$2} $3 == "URL:" {print base($4), len}'
